### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by lifei1245** [Icesythe7/iMorph-TBC#1]
hello,
when i compile the project, i got some errors in dllmain.cpp 
![compile error image](https://github.com/lifei1245/PrivatePicture/blob/master/tbc.png?raw=true)

im poor at c++, the errors show that the params type is incorrect, can not cast the first param from char[1024] to LPWSTR

can u tell me how to reslove it

thanks for your work and sorry for my english and c++skill

**Comment by Icesythe7** [comment]
Change your character set in the solutions properties.

**Comment by lifei1245** [comment]
I compiled success and i got a dll file,it looks the same as the file on the forum(they both  size are 504kb).

i used that file,  when i inject the file by SimpleInject to wow process, the client crashed. and i dont know how to resolve it.

I found a post [here](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-programs/773714-beta-u-morph-morpher-tbc-2-4-3-a.html)  and i download U-Morph, it works fine,but the morph always lost after loading screen,so can you post a new version of U-Morph to github or forum.

thanks alot for your help
